import type { Metadata } from "next";
import "./globals.css";
import { Buda, Poppins, Roboto_Mono, Zalando_Sans_Expanded } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const buda = Zalando_Sans_Expanded({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DSA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${buda.className} antialiased overflow-x-hidden bg-black text-white relative`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
